config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#index'

  resources :posts do
    member do
      post 'like'
    end
    # collection do
    #
    # end
  end

  resources :comments, only: [:destroy]
  post ':object_type/:object_id/comments', to: 'comments#create', as: 'comments'
  # resources :comments, only: [:create]

  resources :users, only: [:show]

  resources :categories, only: %i[show index]

  # створити
  # оновити
  # видалити
  # вивівд або перегляд
  # розміщення , вивів всіх обєктів
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  # belongs_to :post, optional: true
  # belongs_to :comment, optional: true
  belongs_to :object, polymorphic: true # object_id, object_type
  has_many :comments, as: :object
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :image
  has_many_attached :images

  has_many :comments, as: :object
  belongs_to :user
  belongs_to :category

  has_many :likes

  # зв'язки
  # один
  # багато
  #
  # один до одного
  # один до багатьох
  # багато до одного
  # багато до багатьох
  #
  # строгий(сильний)
  # не строгий(слабкий)
  #
  # https://guides.rubyonrails.org/association_basics.html
  # belongs_to - строгий одинарний
  # belongs_to, optional: true, не строгий одинарний
  # has_one - не строгий одинарний
  # has_one :trought
  # has_many - не строгий багато
  # has_many :trought
  # has_and_belongs_to_many - строгий багато

  # Поліморфізм

  def new_view
    update(view_count: (view_count || 0) + 1)
  end

  def photo
    if image.attached?
      image
    else
      '/undefind.png'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  has_many :posts
  has_many :comments, as: :object
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[nickname avatar])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.with_attached_image
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :user_comment, only: [:destroy]

  def create
    params[:comment][:user_id] = current_user.id
    params[:comment][:object_type] = params[:object_type]
    params[:comment][:object_id] = params[:object_id]
    comment = Comment.new(comment_params)
    if comment.save
      redirect_back(fallback_location: root_path)
    else
      pp 'error'
    end
  end

  def destroy
    # @post = comment.post if comment.post
    if @comment.destroy
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def object
    # @object ||= params[:type].constan
  end

  def user_comment
    redirect_back(fallback_location: root_path) unless @comment = current_user.comments.find_by(id: params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text, :object_type, :object_id, :user_id)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @posts = Post.all.with_attached_image
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  before_action :user_post, only: %i[edit update destroy]
  # before_action :post

  def index
    @posts = Post.all.includes(likes: :user).with_attached_image
  end

  def show
    post.new_view
    @comments = post.comments
  end

  def new
    @post = Post.new
  end

  def create
    category = Category.find_or_create_by(name: params[:post][:category])
    @post = current_user.posts.build(post_params)
    @post.category = category
    if post.save
      redirect_to post
    else
      pp 'error' + post
    end
  end

  def edit; end

  def update
    # category = Category.find_or_create(name: params[:post][:category])
    # @post.category = category
    post.update(post_params)
    redirect_to post
  end

  def destredirect_back(fallback_location: root_path)
    post.destroy
    redirect_to posts_path
  end

  def like
    if like = Like.find_by(user_id: current_user.id, post_id: post.id)
      like.destroy
      respond_to do |format|
        format.json { render json: { count: post.likes.count, like: true } }
      end
    else
      # like = Like.find_or_create(user_id: current_user.id, post_id: post.id)
      like = post.likes.build(user_id: current_user.id)
      if like.save
        respond_to do |format|
          format.json { render json: { count: post.likes.size, like: false } }
        end
      else
        respond_to do |format|
          format.json { render json: { error: 'not save' } }
        end
      end
    end
  end

  private

  def post
    @post ||= Post.find(params[:id])
  end

  def user_post
    redirect_back(fallback_location: root_path) unless @post = current_user.posts.find_by(id: params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :body, :image, :category_id, images: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.with_attached_image
    @comments = @user.comments
    @likes = @posts.map { |post| post.likes.size }.sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<li>
<%=link_to category.name, category%>
</li>

app/views/categories/index.html.erb
<h1>Категорії</h1>
<ul>
  <%= render @categories%>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name%></h1>

<div class="row">
  <%= render @posts%>
</div>

app/views/comments/_comment.html.erb
<div id="comment_<%=comment.id%>">
  <p><%= comment.text%></p>
  <span>
    <%= comment.user.email%><%= link_to "delete", comment_path(comment),method: :delete,class:"btn btn-danger" if comment.user_id == current_user.id%>
  </span>
  <%= comment.created_at%>
  <div class="ps-4">

  <%= render "comments/form", object: comment%>
  Коментарі:
  <%=render comment.comments %>
</div>
</div>

app/views/comments/_form.html.erb
<%= form_for :comment, url: comments_path(object.class,object.id),html:{class:"m-3"} do |f| %>
<div class="mb-3">
  <%= f.label :text, class:"form-label" %>
  <%= f.text_field :text, class:"form-control" %>
</div>
  <%= f.submit "Коментувати", class:"btn btn-success"%>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Головна", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Всі пости", posts_path,class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Категорії", categories_path,class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Додати пост", new_post_path,class:"nav-link active"%>
        </li>
      </ul>
      <% if user_signed_in? %>
        <%= link_to user_path(current_user) do %>
          <%= image_tag current_user.avatar, height:50 %>
          <%= current_user.nickname%>
      <%end%>
      <%= link_to "Вихід", destroy_user_session_path, method: :delete, class:"btn btn-danger" %>
    <%else%>
      <%= link_to "Вхід", new_user_session_path, class:"btn btn-success"%>
    <%end%>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails61</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <%= render "layouts/navbar" %>
  <div style="padding: 20px">

    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Головна сторінка</h1>
<div class=row>
<%= render @posts%>
</div>

app/views/posts/_form.html.erb
<%=f.input :title%>
<%=f.input :body, as: :text%>

<%=f.input :category_id, collection: Category.all%>
<%=f.association :category%>

<%= f.input :category %>

<%=f.input :image, as: :file%>

<%=f.input :images, as: :file, input_html:{multiple: true}%>

app/views/posts/_post.html.erb
<div class="col-6 post">
  <%= image_tag post.photo, width:300, height:300 %>
  <b>
    <%= link_to post.title, post_path(post) %>
  </b>
  view:
  <%= post.view_count%><br/>
  likes:
  <span class="likes">
    <%= post.likes.size%>
  </span>

  <button type="button" name="button" onclick="like(this,<%=post.id%>)" class="like-button">
    <%= post.likes.find_by_user_id(current_user.id) ? "DesLike" : "Like" %>
  </button>

  <% if post.user_id == current_user.id %>
    <%= link_to "edit", edit_post_path(post) %>
    <%= link_to "delete", post_path(post), method: :delete%>
  <%end%>
<%= link_to post.category.name, category_path(post.category)%>
</div>

app/views/posts/edit.html.erb
<%= simple_form_for @post do |f| %>
<%= render "form", f:f%>
  <%= f.submit "Редагувати", class:"btn btn-primary"%>
<% end %>

app/views/posts/index.html.erb
<div class="row">
<%= render @posts%>
</div>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <%= render "form", f:f%>
  <%= f.submit "Створити"%>
<% end %>

app/views/posts/show.html.erb
<div class="">
<h1>
  <%= @post.title%>
  <%= link_to "edit", edit_post_path(@post)  if user_signed_in? &&  @post.user_id == current_user.id%>
</h1>
    View: <%= @post.view_count%>
<br/>
   Автор: <%=link_to @post.user.email, user_path(@post.user_id)%><br>
Category: <%=link_to @post.category.name, category_path(@post.category)%>

<%= image_tag @post.photo, width:500, height:300 %>
<p>
<%= @post.body%>
</p>
<div id="images">
  <% @post.images.each do |image|%>
    <%= image_tag image,height:300%>
  <%end%>
</div>
<div id="comments" class="ps-2">
  <%= render "comments/form", object: @post%>
  Коментарі:
  <%=render @comments %>
</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Профіль <%=@user.nickname%></h1>
<div class="row">

<%=render @posts%>
</div>